
title: My Resume
url: 'https://github.com/SumeshPS/online-cv'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6
style: styles-5

#Profile information
name: Sumesh P S
tagline: Full Stack Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: sumesh.sukumaran@gmail.com
phone: 571-386-9247
website: https://sumeshps.github.io/online-cv/
linkedin: Linkedin https://www.linkedin.com/feed/update/urn:li:activity:6259066213029146624
github: SumeshPS
twitter: '@sumeshps2013'



#Update all the sections by editing the files inside _includes folder.
